# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish stable

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    name: Publish to github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Install repo dependencies
        run: yarn install
      - name: Build repo packages
        run: yarn build
      - name: Configure CI Git User
        run: |
          git config --global user.email nachiketmistry@gmail.com
          git config --global user.name Nachiket Mistry
      - name: publish stable package to github
        run: yarn run publish-stable --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
